site_name: Fábrica Docs
docs_dir: docs
theme:
  name: material
  language: pt
  palette:
    - scheme: default
      primary: orange
      toggle:
        icon: material/weather-night
        name: Modo escuro
    - scheme: slate
      primary: orange
      toggle:
        icon: material/weather-sunny
        name: Modo claro

nav:
  - Introdução: index.md
  - OnBoarding: onboarding.md
  - Dicas: tips.md
  - Boas Práticas: best-practices.md
  - Começando um novo projeto: create-project.md
  - Padrões de Projeto:
      - Criando um Projeto Django: init-back.md
      - Criando um Projeto Vue: init-vue.md

markdown_extensions:
  - admonition
  - codehilite
  - toc:
      permalink: true
  - pymdownx.tabbed:
      alternate_style: true
  - pymdownx.superfences
  - pymdownx.details          
  - pymdownx.snippets          
  - pymdownx.highlight         

extra:
  generator: false
